# Site settings
title: Caribbean Cruises
client:
  name: Royal Caribbean International
  link: "https://www.royalcaribbean.co.uk/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Island-hop aboard a Royal Caribbean cruise and discover the island life, from the jungles of St Lucia to the secluded bays of Antigua. Whether you’re looking for warm waters, shady palm trees and golden sands, or fiery cuisine, island rhythms and vibrant culture, find it all in your dream Caribbean cruise.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/royal-caribbean" # the subpath of your site, e.g. /blog/
img:     "/royal-caribbean/_assets/img"
css:     "/royal-caribbean/_assets/css"
js:      "/royal-caribbean/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed